baseURL: https://fanciful-bubblegum-ca781f.netlify.app/
# Uncomment below to use aafu as hugo theme. See instructions in README.md
theme: aafu
languageCode: en-us
build:
  writeStats: true
params:
  title: Portfolio
  author: Abdelilah YAAZZA
  description: AbdelilahYAAAZZA's Portfolio
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Cloudflare](https://www.cloudflare.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Abdelilah YAAZZA."
    tagline: Cybersecurity Student
    location: "Casablanca, MA"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "www.linkedin.com/in/abdelilah-yaazza-9b784b330"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/AbdelilahYaazza"
        title: GitHub
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: I'm a passionate cybersecurity student with a strong interest in ethical hacking, system security, and digital forensics. I enjoy exploring how systems work, identifying vulnerabilities, and building secure solutions.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Cybersecurity Intern
        dates: 2025 - *Present*
        company: 
        details: |1-
          - Assisted in identifying and patching security vulnerabilities in internal systems.
          - Conducted basic penetration tests and helped monitor network traffic for potential threats.
          - Gained hands-on experience with tools like Wireshark, Burp Suite, and Kali Linux.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list :
      - degree: engineering diplome
        college: Institut national des posts et telecommunication
        dates: 2004 - 2009
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: SecureShell
        url: "#"
        description: Developed a simple, secure file-sharing shell script using SSH and SCP for encrypted data transfer between local and remote systems.
      - title: Network Sniffer
        url: "#"
        description: Built a basic packet sniffer using Python and Scapy to capture and analyze live network traffic on a local network.
      - title: Password Cracker
        url: "#"
        description: Designed a Python-based tool that performs dictionary attacks on hashed passwords for educational purposes in a controlled lab environment.
      - title: Phishing Simulation
        url: "#"
        description: Created a phishing simulation using a cloned login page to study user behavior and demonstrate the importance of awareness training.

  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: Wireshark
        skillrating: 90
      - skill: Metasploite
        skillrating: 50
      - skill: John The Ripper
        skillrating: 45
      - skill: Nmap
        skillrating: 90
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Programming
      - hobby: Scanning
      - hobby: Reading
